import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:go_router/go_router.dart';
import 'package:google_fonts/google_fonts.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_dimensions.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../shared/widgets/fluenta_button.dart';
import '../../../shared/widgets/skill_chip.dart';

class OnboardingScreen extends ConsumerStatefulWidget {
  const OnboardingScreen({super.key});

  @override
  ConsumerState<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends ConsumerState<OnboardingScreen> with TickerProviderStateMixin {
  final _pageController = PageController();
  int _currentPage = 0;
  late AnimationController _pulseController;

  final List<OnboardingData> _pages = [
    OnboardingData(
      title: 'AI Personalized Path',
      description: 'Forget generic worksheets. Every Voce lesson is dynamically generated by AI based on your precise goals, level, and interests.',
      icon: Icons.auto_awesome,
      colors: [Color(0xFF38BDF8), Color(0xFFC084FC)],
      accentText: "AI CURRICULUM",
    ),
    OnboardingData(
      title: 'Synchronized Skills',
      description: 'Achieve true bilingualism by practicing Reading, Writing, Listening, and Speaking simultaneously inside every singular task.',
      icon: Icons.graphic_eq_outlined,
      colors: [Color(0xFFF43F5E), Color(0xFFFB923C)],
      accentText: "4-CORE MASTERY",
    ),
    OnboardingData(
      title: 'Social Voice Chatrooms',
      description: 'Step into interactive group lobbies and 1-on-1 peer direct messages. Speak aloud, exchange notes, and learn with friends.',
      icon: Icons.forum_outlined,
      colors: [Color(0xFF10B981), Color(0xFF34D399)],
      accentText: "PEER COMMUNITY",
    ),
  ];

  @override
  void initState() {
    super.initState();
    _pulseController = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 2000),
    )..repeat(reverse: true);
  }

  @override
  void dispose() {
    _pageController.dispose();
    _pulseController.dispose();
    super.dispose();
  }

  void _completeOnboarding() {
    context.go('/signup');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background, // Warm off-white background
      body: Stack(
        children: [
          // Top Left & Bottom Right Glowing Background Accents
          Positioned(
            top: -100,
            left: -100,
            child: Container(
              width: 250,
              height: 250,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: _pages[_currentPage].colors[0].withOpacity(0.08),
                    blurRadius: 100,
                    spreadRadius: 50,
                  ),
                ],
              ),
            ),
          ),
          Positioned(
            bottom: -50,
            right: -50,
            child: Container(
              width: 300,
              height: 300,
              decoration: BoxDecoration(
                shape: BoxShape.circle,
                boxShadow: [
                  BoxShadow(
                    color: _pages[_currentPage].colors[1].withOpacity(0.08),
                    blurRadius: 120,
                    spreadRadius: 60,
                  ),
                ],
              ),
            ),
          ),

          // Upper Navigation Headers (Skip Button)
          Positioned(
            top: 50,
            left: 24,
            right: 24,
            child: Row(
              mainAxisAlignment: MainAxisAlignment.spaceBetween,
              children: [
                Text(
                  "Voce",
                  style: GoogleFonts.outfit(
                    color: AppColors.primary,
                    fontSize: 20,
                    fontWeight: FontWeight.w800,
                    letterSpacing: 1.0,
                  ),
                ),
                GestureDetector(
                  onTap: _completeOnboarding,
                  child: Container(
                    padding: const EdgeInsets.symmetric(horizontal: 14, vertical: 8),
                    decoration: BoxDecoration(
                      color: AppColors.primary.withOpacity(0.04),
                      borderRadius: BorderRadius.circular(20),
                      border: Border.all(color: AppColors.border),
                    ),
                    child: Text(
                      "Skip",
                      style: GoogleFonts.outfit(
                        color: AppColors.textSecondary,
                        fontSize: 12,
                        fontWeight: FontWeight.w600,
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),

          // Sliding Page Contents
          Column(
            children: [
              const SizedBox(height: 100),
              Expanded(
                child: PageView.builder(
                  controller: _pageController,
                  onPageChanged: (v) => setState(() => _currentPage = v),
                  itemCount: _pages.length,
                  itemBuilder: (context, index) {
                    final data = _pages[index];
                    return SingleChildScrollView(
                      padding: const EdgeInsets.symmetric(horizontal: 32),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          const SizedBox(height: 24),
                          // Multi-layered visual card
                          ScaleTransition(
                            scale: Tween<double>(begin: 0.95, end: 1.0).animate(
                              CurvedAnimation(parent: _pulseController, curve: Curves.easeInOut),
                            ),
                            child: Container(
                              height: 240,
                              width: 240,
                              child: Stack(
                                alignment: Alignment.center,
                                children: [
                                  // Outer glowing circular border
                                  Container(
                                    decoration: BoxDecoration(
                                      shape: BoxShape.circle,
                                      border: Border.all(
                                        color: data.colors[0].withOpacity(0.2),
                                        width: 1.5,
                                      ),
                                    ),
                                  ),
                                  // Middle rotating glassmorphic card
                                  Container(
                                    margin: const EdgeInsets.all(20),
                                    decoration: BoxDecoration(
                                      shape: BoxShape.circle,
                                      gradient: LinearGradient(
                                        colors: [
                                          data.colors[0].withOpacity(0.12),
                                          data.colors[1].withOpacity(0.01),
                                        ],
                                        begin: Alignment.topLeft,
                                        end: Alignment.bottomRight,
                                      ),
                                    ),
                                  ),
                                  // Central elevated visual circle
                                  Container(
                                    margin: const EdgeInsets.all(40),
                                    decoration: BoxDecoration(
                                      shape: BoxShape.circle,
                                      color: Colors.white,
                                      border: Border.all(
                                        color: AppColors.border,
                                        width: 1.0,
                                      ),
                                      boxShadow: [
                                        BoxShadow(
                                          color: data.colors[0].withOpacity(0.12),
                                          blurRadius: 20,
                                          spreadRadius: 1,
                                        )
                                      ],
                                    ),
                                    child: Center(
                                      child: Icon(
                                        data.icon,
                                        size: 60,
                                        color: data.colors[0],
                                      ),
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ),
                          const SizedBox(height: 40),
                          // Category badge chip
                          Container(
                            padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                            decoration: BoxDecoration(
                              color: data.colors[0].withOpacity(0.12),
                              borderRadius: BorderRadius.circular(20),
                              border: Border.all(color: data.colors[0].withOpacity(0.3)),
                            ),
                            child: Text(
                              data.accentText,
                              style: GoogleFonts.outfit(
                                color: data.colors[0],
                                fontSize: 10,
                                fontWeight: FontWeight.w800,
                                letterSpacing: 2.0,
                              ),
                            ),
                          ),
                          const SizedBox(height: 16),
                          // Head Title
                          Text(
                            data.title,
                            style: GoogleFonts.outfit(
                              color: AppColors.textPrimary,
                              fontSize: 28,
                              fontWeight: FontWeight.w800,
                              letterSpacing: -0.5,
                            ),
                            textAlign: TextAlign.center,
                          ),
                          const SizedBox(height: 12),
                          // Description
                          Text(
                            data.description,
                            style: GoogleFonts.outfit(
                              color: AppColors.textSecondary,
                              fontSize: 14,
                              fontWeight: FontWeight.w400,
                              height: 1.5,
                            ),
                            textAlign: TextAlign.center,
                          ),
                          
                          // Skill chips for the Skills slide
                          if (index == 1) ...[
                            const SizedBox(height: 24),
                            const Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              alignment: WrapAlignment.center,
                              children: [
                                SkillChip(skill: 'reading'),
                                SkillChip(skill: 'writing'),
                                SkillChip(skill: 'listening'),
                                SkillChip(skill: 'speaking'),
                              ],
                            ),
                          ],
                        ],
                      ),
                    );
                  },
                ),
              ),

              // Bottom Progress Controller & Action Button
              Padding(
                padding: const EdgeInsets.only(left: 32, right: 32, bottom: 48),
                child: Column(
                  children: [
                    // Dynamic Page Indicator Dots (Pills!)
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: List.generate(
                        _pages.length,
                        (index) => AnimatedContainer(
                          duration: const Duration(milliseconds: 300),
                          width: _currentPage == index ? 24 : 8,
                          height: 8,
                          margin: const EdgeInsets.symmetric(horizontal: 4),
                          decoration: BoxDecoration(
                            borderRadius: BorderRadius.circular(10),
                            color: _currentPage == index
                                ? _pages[_currentPage].colors[0]
                                : AppColors.borderStrong,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 32),
                    // Action button
                    FluentaButton(
                      text: _currentPage == _pages.length - 1 ? 'Get Started' : 'Next',
                      onPressed: () {
                        if (_currentPage < _pages.length - 1) {
                          _pageController.nextPage(
                            duration: const Duration(milliseconds: 450),
                            curve: Curves.easeInOutCubic,
                          );
                        } else {
                          _completeOnboarding();
                        }
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class OnboardingData {
  final String title;
  final String description;
  final IconData icon;
  final List<Color> colors;
  final String accentText;

  OnboardingData({
    required this.title,
    required this.description,
    required this.icon,
    required this.colors,
    required this.accentText,
  });
}
