import 'package:flutter/material.dart';
import 'package:go_router/go_router.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_dimensions.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../shared/widgets/fluenta_button.dart';
import '../../../shared/widgets/fluenta_text_field.dart';
import '../../../shared/widgets/skill_chip.dart';

class OnboardingScreen extends StatefulWidget {
  const OnboardingScreen({super.key});

  @override
  State<OnboardingScreen> createState() => _OnboardingScreenState();
}

class _OnboardingScreenState extends State<OnboardingScreen> {
  final _pageController = PageController();
  int _currentPage = 0;
  bool _showForm = false;

  final _goalController = TextEditingController();
  final _languageController = TextEditingController();

  final List<OnboardingData> _pages = [
    OnboardingData(
      title: 'Learn your way',
      description: 'Every lesson is dynamically generated by AI based on your level, goals, and interests.',
      icon: Icons.auto_awesome,
      color: AppColors.primary,
    ),
    OnboardingData(
      title: 'All 4 skills',
      description: 'Master reading, writing, listening, and speaking in every single lesson. No exceptions.',
      icon: Icons.school,
      color: AppColors.reading,
    ),
    OnboardingData(
      title: 'Join the community',
      description: 'Interact with other learners, share recordings, and get feedback in real-time.',
      icon: Icons.forum,
      color: AppColors.writing,
    ),
  ];

  @override
  void dispose() {
    _pageController.dispose();
    _goalController.dispose();
    _languageController.dispose();
    super.dispose();
  }

  Future<void> _completeOnboarding() async {
    final userId = Supabase.instance.client.auth.currentUser!.id;
    await Supabase.instance.client.from('profiles').update({
      'goal': _goalController.text.trim(),
      'native_language': _languageController.text.trim(),
    }).eq('id', userId);

    if (mounted) {
      context.go('/placement');
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.background,
      body: Stack(
        children: [
          Column(
            children: [
              Expanded(
                child: PageView.builder(
                  controller: _pageController,
                  onPageChanged: (v) => setState(() => _currentPage = v),
                  itemCount: _pages.length,
                  itemBuilder: (context, index) {
                    final data = _pages[index];
                    return Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 40),
                      child: Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Container(
                            height: 240,
                            width: 240,
                            decoration: BoxDecoration(
                              color: data.color.withOpacity(0.1),
                              shape: BoxShape.circle,
                            ),
                            child: Icon(
                              data.icon,
                              size: 100,
                              color: data.color,
                            ),
                          ),
                          const SizedBox(height: 48),
                          Text(
                            data.title,
                            style: AppTextStyles.display2,
                            textAlign: TextAlign.center,
                          ),
                          const SizedBox(height: 16),
                          Text(
                            data.description,
                            style: AppTextStyles.bodyMedium,
                            textAlign: TextAlign.center,
                          ),
                          if (index == 1) ...[
                            const SizedBox(height: 24),
                            const Wrap(
                              spacing: 8,
                              runSpacing: 8,
                              alignment: WrapAlignment.center,
                              children: [
                                SkillChip(skill: 'reading'),
                                SkillChip(skill: 'writing'),
                                SkillChip(skill: 'listening'),
                                SkillChip(skill: 'speaking'),
                              ],
                            ),
                          ],
                        ],
                      ),
                    );
                  },
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(AppDimensions.s32),
                child: Column(
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: List.generate(
                        _pages.length,
                        (index) => Container(
                          width: 8,
                          height: 8,
                          margin: const EdgeInsets.symmetric(horizontal: 4),
                          decoration: BoxDecoration(
                            shape: BoxShape.circle,
                            color: _currentPage == index
                                ? AppColors.primary
                                : AppColors.border,
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(height: 32),
                    FluentaButton(
                      text: _currentPage == _pages.length - 1 ? 'Get Started' : 'Next',
                      onPressed: () {
                        if (_currentPage < _pages.length - 1) {
                          _pageController.nextPage(
                            duration: const Duration(milliseconds: 300),
                            curve: Curves.easeOut,
                          );
                        } else {
                          setState(() => _showForm = true);
                        }
                      },
                    ),
                  ],
                ),
              ),
            ],
          ),
          if (_showForm)
            _buildFormOverlay(),
        ],
      ),
    );
  }

  Widget _buildFormOverlay() {
    return AnimatedContainer(
      duration: const Duration(milliseconds: 400),
      curve: Curves.easeOutCubic,
      color: Colors.black.withOpacity(0.4),
      child: Align(
        alignment: Alignment.bottomCenter,
        child: Container(
          padding: const EdgeInsets.all(AppDimensions.s32),
          decoration: const BoxDecoration(
            color: Colors.white,
            borderRadius: BorderRadius.vertical(
              top: Radius.circular(AppDimensions.radiusXL),
            ),
          ),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text("Tell us about yourself", style: AppTextStyles.h1),
              const SizedBox(height: AppDimensions.s8),
              Text(
                "This helps Lex personalize your lessons.",
                style: AppTextStyles.bodyMedium,
              ),
              const SizedBox(height: AppDimensions.s32),
              FluentaTextField(
                label: "What's your main goal?",
                controller: _goalController,
                hintText: "Job, Travel, Academic, General...",
                prefixIcon: Icons.flag_outlined,
              ),
              const SizedBox(height: AppDimensions.s20),
              FluentaTextField(
                label: "What's your native language?",
                controller: _languageController,
                hintText: "Spanish, Arabic, Chinese...",
                prefixIcon: Icons.translate,
              ),
              const SizedBox(height: AppDimensions.s40),
              FluentaButton(
                text: "Start My Assessment",
                onPressed: _completeOnboarding,
              ),
              SizedBox(height: MediaQuery.of(context).viewInsets.bottom),
            ],
          ),
        ),
      ),
    );
  }
}

class OnboardingData {
  final String title;
  final String description;
  final IconData icon;
  final Color color;

  OnboardingData({
    required this.title,
    required this.description,
    required this.icon,
    required this.color,
  });
}
