import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

serve(async (req) => {
  const { level, topic, focusSkill, weakAreas, userGoal, youtubeVideoTitle } = await req.json()
  const GEMINI_KEY = Deno.env.get('GEMINI_API_KEY')!

  const prompt = `You are an expert English teacher creating a lesson for a ${level} level student.

Lesson Topic: "${topic}"
Focus Skill: ${focusSkill}
Related YouTube Video Title: "${youtubeVideoTitle || 'None specified'}"
Student's Weak Areas: ${weakAreas?.join(', ') || 'none identified yet'}
Student's Goal: ${userGoal || 'general fluency'}

IMPORTANT: If a Related YouTube Video Title is provided above and the Focus Skill is listening, make sure that the generated "listening_transcript" and the "listening_exercises" match the exact context, vocabulary, and theme of that YouTube video extremely closely! This ensures the video and the transcript feel perfectly unified.

Create a complete, engaging lesson. Return ONLY a JSON object with NO markdown, NO backticks, NO extra text:
{
  "grammar_explanation": "Clear, human explanation of the key grammar point. Use simple words. Include 3 real-life examples as sentences. End with one tip to remember it.",
  "vocabulary_list": [
    {"word": "", "definition": "", "example": "", "level": "${level}"}
  ],
  "reading_passage": "An engaging 150-200 word passage using the grammar and vocabulary. Make it feel like something real — a blog post, a story, a letter, not a textbook.",
  "reading_questions": [
    {"id": "r1", "question": "", "type": "mcq", "options": ["", "", "", ""], "answer": ""},
    {"id": "r2", "question": "", "type": "mcq", "options": ["", "", "", ""], "answer": ""},
    {"id": "r3", "question": "", "type": "open_ended", "answer_key": ""}
  ],
  "listening_transcript": "A realistic 100-120 word conversation or monologue that matches the theme of the specified YouTube video. Make it sound like real speech, not a script.",
  "listening_exercises": [
    {"id": "l1", "question": "An open-ended comprehension question testing understanding of the video topic", "model_answer": "A clear, helpful model answer for the student to compare their answer against."},
    {"id": "l2", "question": "An open-ended comprehension question testing understanding of the video topic", "model_answer": "A clear, helpful model answer for the student to compare their answer against."},
    {"id": "l3", "question": "An open-ended comprehension question testing understanding of the video topic", "model_answer": "A clear, helpful model answer for the student to compare their answer against."}
  ],
  "writing_prompt": "A clear, specific writing task (2-3 sentences explaining what to write). Make it real and relevant to everyday life.",
  "speaking_prompt": "A clear speaking task the student will record. Should feel like a natural conversation starter, not an exam prompt."
}`

  try {
    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/gemini-3.1-flash-lite:generateContent?key=${GEMINI_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          contents: [{ parts: [{ text: prompt }] }],
          generationConfig: { temperature: 0.7, maxOutputTokens: 3000 },
        }),
      }
    )

    if (!response.ok) {
      const errorData = await response.json()
      console.error('Gemini API Error:', errorData)
      throw new Error(`Gemini API returned ${response.status}: ${JSON.stringify(errorData)}`)
    }

    const data = await response.json()
    
    if (!data.candidates || data.candidates.length === 0) {
      console.error('No candidates in Gemini response:', data)
      throw new Error('No content generated by Gemini')
    }

    const text = data.candidates[0].content.parts[0].text
    const clean = text.replace(/```json|```/g, '').trim()

    // Validate that it's valid JSON before returning
    try {
      JSON.parse(clean)
    } catch (e) {
      console.error('Gemini returned invalid JSON:', text)
      throw new Error('AI generated invalid curriculum format')
    }

    return new Response(clean, {
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
    })
  } catch (error) {
    console.error('Function execution error:', error)
    return new Response(JSON.stringify({ error: error.message }), {
      status: 500,
      headers: { 'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*' },
    })
  }
})
